---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "nornir_data/hosts.yaml"
        group_file: "nornir_data/groups.yaml"
        defaults_file: "nornir_data/defaults.yaml"

runner:
    plugin: threaded
    options:
        num_workers: 100

ssh:
    config_file: True
